"""
main.py (FastAPI app)

Serves two things for any item_id:
1. A 28-day sales forecast from the trained LightGBM model
2. Inventory recommendations (safety stock, reorder point) derived from that forecast

Run with: uv run uvicorn app.main:app --reload
Then visit: http://127.0.0.1:8000/docs for interactive API documentation (auto-generated by FastAPI)
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
import numpy as np
import lightgbm as lgb

from src.models.lgbm_model import FEATURE_COLS, add_item_features, train_test_split_by_date
from src.inventory import compute_item_inventory_plan

app = FastAPI(title="Demand Forecasting & Inventory API")

# Allow the React frontend (running on a different port) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # fine for local dev; restrict in real production
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load model + data once at startup, not on every request (keeps API fast)
DF = pd.read_parquet("data/processed/ca1_foods_features.parquet")
_, _, CUTOFF_DATE = train_test_split_by_date(DF, test_days=28)
DF = add_item_features(DF, train_cutoff_date=CUTOFF_DATE)
TRAIN, TEST, _ = train_test_split_by_date(DF, test_days=28)
BOOSTER = lgb.Booster(model_file="outputs/lgbm_model.txt")


@app.get("/")
def root():
    return {"message": "Demand Forecasting API is running. See /docs for usage."}


@app.get("/items")
def list_items():
    """Returns all available item_ids the model can forecast for."""
    items = sorted(DF["item_id"].unique().tolist())
    return {"count": len(items), "items": items}


@app.get("/forecast/{item_id}")
def get_forecast(item_id: str, lead_time_days: int = 7, service_level: float = 0.95):
    """
    Returns a 28-day forecast plus inventory recommendations for a given item_id.

    Query params:
    - lead_time_days: days between placing and receiving an order (default 7)
    - service_level: target probability of avoiding stockouts (default 0.95)
    """
    item_test = TEST[TEST["item_id"] == item_id].sort_values("date")

    if item_test.empty:
        raise HTTPException(status_code=404, detail=f"item_id '{item_id}' not found")

    pred_log = BOOSTER.predict(item_test[FEATURE_COLS])
    forecast = np.expm1(pred_log)
    forecast = np.clip(forecast, 0, None)

    inventory_plan = compute_item_inventory_plan(
        pd.Series(forecast), lead_time_days=lead_time_days, service_level=service_level
    )

    return {
        "item_id": item_id,
        "dates": item_test["date"].dt.strftime("%Y-%m-%d").tolist(),
        "forecast": [round(float(f), 2) for f in forecast],
        "actual_sales": item_test["sales"].tolist(),
        "inventory_plan": inventory_plan,
    }